export const ROUTES = {
  home: "/main",
  usedgoods: "/usedgoods",
  jobs: "/job",
  rental: "/rental",
  go: "/go",
  create: "/create",
  notifications: "/notifications",
  login: "/login",
  myProfile: "/profile",
  favorites: "/favorites",
  myPosts: "/myposts",
  report: "/report",
  termsOfService: "/terms/policy",
  privacyPolicy: "/terms/privacy",
  youthPolicy: "/terms/youth",
  admin: "/admin",
  adminReports: "/admin/reports",
  paymentReturn: "/payment/return",
} as const;
