export const ROUTES = {
  home: "/main",
  usedgoods: "/usedgoods",
  jobs: "/job",
  rental: "/rental",
  community: "/community",
  dating: "/dating",
  create: "/create",
  notifications: "/notifications",
  login: "/login",
  myProfile: "/profile",
  favorites: "/favorites",
  myPosts: "/myposts",
  chat: "/chat",
  chatRoom: (id: string | number) => `/chat/${id}`,
  report: "/report",
  termsOfService: "/terms/policy",
  privacyPolicy: "/terms/privacy",
  youthPolicy: "/terms/youth",
} as const;
