export const ROUTES = {
  home: "/home",
  usedgoods: "/usedgoods",
  jobs: "/job",
  rental: "/rental",
  community: "/community",
  dating: "/dating",
  create: "/create",
  notifications: "/notifications",
  login: "/login",
  myProfile: "/my-profile",
  favorites: "/favorites",
  myPosts: "/my-posts",
  chat: "/chat",
  chatRoom: (id: string | number) => `/chat/${id}`,
  report: "/report",
  termsOfService: "/terms?tab=terms",
  privacyPolicy: "/terms?tab=privacy",
  locationPolicy: "/terms?tab=location",
} as const;
