import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { GlobalLayout } from "@/components/common/GlobalLayout";
import { getSessionUser } from "@/services/user/user";
import { BCP47_LOCALE, type Locale } from "@/i18n/config";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialUser = await getSessionUser();
  const locale = (await getLocale()) as Locale;

  return (
    <html
      lang={BCP47_LOCALE[locale]}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        {/* 하이드레이션 전에 실행: 새로고침으로 채팅 오버레이가 복원될 상황이면
            모바일에서 흰 커버(globals.css)를 깔아 밑 페이지 깜빡임을 막는다.
            'chatWidget:newChatDraft' 키는 FloatingChatWidget의 NEW_CHAT_DRAFT_KEY와 일치시켜야 한다. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `try{if(innerWidth<768){var c=new URLSearchParams(location.search).get('chat');if(c||sessionStorage.getItem('chatWidget:newChatDraft'))document.documentElement.setAttribute('data-chat-boot','')}}catch(e){}`,
          }}
        />
        <NextIntlClientProvider>
          <GlobalLayout initialUser={initialUser}>{children}</GlobalLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
