import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GlobalLayout } from "@/components/common/GlobalLayout";
import { getSessionUser } from "@/services/user/user";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialUser = await getSessionUser();

  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GlobalLayout initialUser={initialUser}>{children}</GlobalLayout>
      </body>
    </html>
  );
}
